# 应用名称
spring:
  application:
    name: mall-gateway

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.3.5:8848
        namespace: public


