GET http://localhost:8080/brand/list?pageNum=1&pageSize=10
Accept: application/json

###
GET http://localhost:8080/productCategory/list/withChildren
Accept: application/json

###
POST http://localhost:8080/admin/register
Content-Type: application/json

{
  "username": "ethan",
  "password": "123456",
  "icon": "",
  "email": "15270855286",
  "nickName": "",
  "note": ""
}

###
