POST http://localhost:8080/role/allocMenu?roleId=1&menuIds=[1]
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNyZWF0ZWQiOjE2NDExMDg3Nzg5MDgsImV4cCI6MTY0MTEwOTM4M30.6Eg04AME6fke26gSaWZ17-Wx-kfcFJk75FLlRUCrBGZApve3oQU8zHx_IBwkfi7Piq1IU6zw4eOhXdsK68gt-w

###
###
POST http://localhost:8080/admin/login
Content-Type: application/json

{
  "username": "test",
  "password": "123456"
}

###
GET http://localhost:8080/subject/listAll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiY3JlYXRlZCI6MTY0MTA1MDMwNzE4MSwiZXhwIjoxNjQxMDUwOTExfQ.Ed-YG-6QHQA3C6ULepychBLtfnQXpe8IB35d-VYVhbmeXhFPogtWTnZZZrHwTfZzu5Q_EMfuicnU3qONTZ2pkw
Accept: application/json

###
GET http://localhost:8080/aliyun/oss/initPostData
Accept: application/json

###
GET http://localhost:8080/brand/list?pageNum=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiY3JlYXRlZCI6MTY0MTA0OTY3MDMzOCwiZXhwIjoxNjQxMDUwMjc1fQ.peLRvu9xMk0gTLWDCmEuiGnWVVBlxXMbtZSbUm78wow6tVola5oYwzuPQ760FiEqDvBV8EYCT0wQwTTre09ONg
Accept: application/json

###
GET http://localhost:8080/productCategory/list/withChildren
Accept: application/json

###
POST http://localhost:8080/admin/register
Content-Type: application/json

{
  "username": "ethan",
  "password": "123456",
  "icon": "",
  "email": "15270855286",
  "nickName": "",
  "note": ""
}

###
