GET http://localhost:8201/mall-admin/admin/info
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ0ZXN0Iiwic2NvcGUiOlsiYWxsIl0sImlkIjoxLCJleHAiOjE2NDI0MTA4ODksImF1dGhvcml0aWVzIjpbIjNf6LaF57qn566h55CG5ZGYIl0sImp0aSI6IjllNGY3YTQ0LTgxYTEtNGUwNi05NjY1LTM1NTIyZWU5OGYyMCIsImNsaWVudF9pZCI6ImFkbWluLWFwcCJ9.YntUqilMB4TcPx0y_q0ELV_1v10v9FuwQjWhQgIjAkt_s_dGZzMqvW5IZOVgkPeCS917UPo2ICGE3ZLUPEFaGXqxcdu7uLTJNv0k8JspPM4oB3VUPk_MtX8T_wXSSj0IQUUa5Oa-yagQTGq903Cpu0Xb8mAFKrTIxn35JxaXw3UMoU8jWVpcYUrMxrXbHYZeoakPuRZayrwhMvubLfXISNFbD7bZ0ce49O-dvJyWIqiA-26mLaY1zHugzLpMPrz_wghxh_ZzX1ZwHmki1ODtLyW6F1mwiBAzNSX8_8e9zET-DgUmhAc5vTqHigcleM6f7UJKIFmkz7nvP0PxZUT1Pg
Accept: application/json

###
POST http://localhost:8080/role/allocMenu?roleId=1&menuIds=[1]
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImNyZWF0ZWQiOjE2NDExMDg3Nzg5MDgsImV4cCI6MTY0MTEwOTM4M30.6Eg04AME6fke26gSaWZ17-Wx-kfcFJk75FLlRUCrBGZApve3oQU8zHx_IBwkfi7Piq1IU6zw4eOhXdsK68gt-w

###
###
POST http://localhost:8201/mall-admin/admin/login
Content-Type: application/json

{
  "username": "test",
  "password": "123456"
}

###
GET http://localhost:8201/mall-admin/subject/listAll
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ0ZXN0Iiwic2NvcGUiOlsiYWxsIl0sImlkIjoxLCJleHAiOjE2NDI0MTA4ODksImF1dGhvcml0aWVzIjpbIjNf6LaF57qn566h55CG5ZGYIl0sImp0aSI6IjllNGY3YTQ0LTgxYTEtNGUwNi05NjY1LTM1NTIyZWU5OGYyMCIsImNsaWVudF9pZCI6ImFkbWluLWFwcCJ9.YntUqilMB4TcPx0y_q0ELV_1v10v9FuwQjWhQgIjAkt_s_dGZzMqvW5IZOVgkPeCS917UPo2ICGE3ZLUPEFaGXqxcdu7uLTJNv0k8JspPM4oB3VUPk_MtX8T_wXSSj0IQUUa5Oa-yagQTGq903Cpu0Xb8mAFKrTIxn35JxaXw3UMoU8jWVpcYUrMxrXbHYZeoakPuRZayrwhMvubLfXISNFbD7bZ0ce49O-dvJyWIqiA-26mLaY1zHugzLpMPrz_wghxh_ZzX1ZwHmki1ODtLyW6F1mwiBAzNSX8_8e9zET-DgUmhAc5vTqHigcleM6f7UJKIFmkz7nvP0PxZUT1Pg
Accept: application/json

###
GET http://localhost:8080/aliyun/oss/initPostData
Accept: application/json

###
GET http://localhost:8080/brand/list?pageNum=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiY3JlYXRlZCI6MTY0MTA0OTY3MDMzOCwiZXhwIjoxNjQxMDUwMjc1fQ.peLRvu9xMk0gTLWDCmEuiGnWVVBlxXMbtZSbUm78wow6tVola5oYwzuPQ760FiEqDvBV8EYCT0wQwTTre09ONg
Accept: application/json

###
GET http://localhost:8080/productCategory/list/withChildren
Accept: application/json

###
POST http://localhost:8080/admin/register
Content-Type: application/json

{
  "username": "ethan",
  "password": "123456",
  "icon": "",
  "email": "15270855286",
  "nickName": "",
  "note": ""
}

###
