server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  mapper-locations:
    - mapper/*.xml
    - dao/*.xml
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tPsVb7b1DktXAT9nUbP # 访问身份验证中用到用户标识
    accessKeySecret: Y8XatePpBknQ2D74lYuSuVqUe72XnX # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ethan-oss-dev # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://mipyij.natappfree.cc/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: emall/images/ # 上传文件夹路径前缀